# permissions for end users to edit authconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authconfig-editor-role
rules:
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - authorino.kuadrant.io
  resources:
  - authconfigs/status
  verbs:
  - get
