apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  name: webhooks
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: webhooks
        image: authorino:local
        imagePullPolicy: IfNotPresent
        command:
        - authorino
        - webhooks
        ports:
        - name: webhooks
          containerPort: 9443
        - name: metrics
          containerPort: 8080
        - name: healthz
          containerPort: 8081
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        resources: {}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: authorino-webhook-server-cert
