apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- deployment.yaml
- service.yaml
- rbac.yaml
- ../crd

patchesStrategicMerge:
- patches/webhook_in_authconfigs.yaml

commonLabels:
  app: authorino
  authorino-component: authorino-webhooks

namespace: authorino-webhooks

namePrefix: authorino-

replacements:
- source:
    fieldPath: .metadata.namespace
    group: cert-manager.io
    kind: Certificate
    name: authorino-webhook-server-cert
    version: v1
  targets:
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
    select:
      kind: CustomResourceDefinition
- source:
    fieldPath: .metadata.name
    group: cert-manager.io
    kind: Certificate
    name: authorino-webhook-server-cert
    version: v1
  targets:
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
      index: 1
    select:
      kind: CustomResourceDefinition
- source:
    fieldPath: .metadata.name
    kind: Service
    name: authorino-webhooks
    version: v1
  targets:
  - fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      create: true
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: authorino-webhook-server-cert
      version: v1
  - fieldPaths:
    - .spec.conversion.webhook.clientConfig.service.name
    options:
      create: true
    select:
      kind: CustomResourceDefinition
- source:
    fieldPath: .metadata.namespace
    kind: Service
    name: authorino-webhooks
    version: v1
  targets:
  - fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      create: true
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: authorino-webhook-server-cert
      version: v1
  - fieldPaths:
    - .spec.conversion.webhook.clientConfig.service.namespace
    options:
      create: true
    select:
      kind: CustomResourceDefinition
  - fieldPaths:
    - subjects.0.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: authorino-webhooks-manager
