apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    authorino-instance: $(AUTHORINO_INSTANCE)
  name: $(AUTHORINO_INSTANCE)-ca-root
  namespace: $(NAMESPACE)
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    authorino-instance: $(AUTHORINO_INSTANCE)
  name: $(AUTHORINO_INSTANCE)-ca-cert
  namespace: $(NAMESPACE)
spec:
  commonName: '*.$(NAMESPACE).svc'
  isCA: true
  issuerRef:
    kind: Issuer
    name: $(AUTHORINO_INSTANCE)-ca-root
  secretName: $(AUTHORINO_INSTANCE)-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    authorino-instance: $(AUTHORINO_INSTANCE)
  name: $(AUTHORINO_INSTANCE)-ca
  namespace: $(NAMESPACE)
spec:
  ca:
    secretName: $(AUTHORINO_INSTANCE)-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    authorino-instance: $(AUTHORINO_INSTANCE)
  name: $(AUTHORINO_INSTANCE)-oidc-server-cert
  namespace: $(NAMESPACE)
spec:
  dnsNames:
  - $(AUTHORINO_INSTANCE)-authorino-oidc
  - $(AUTHORINO_INSTANCE)-authorino-oidc.$(NAMESPACE).svc
  - $(AUTHORINO_INSTANCE)-authorino-oidc.$(NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: $(AUTHORINO_INSTANCE)-ca
  secretName: $(AUTHORINO_INSTANCE)-oidc-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    authorino-instance: $(AUTHORINO_INSTANCE)
  name: $(AUTHORINO_INSTANCE)-server-cert
  namespace: $(NAMESPACE)
spec:
  dnsNames:
  - $(AUTHORINO_INSTANCE)-authorino-authorization
  - $(AUTHORINO_INSTANCE)-authorino-authorization.$(NAMESPACE).svc
  - $(AUTHORINO_INSTANCE)-authorino-authorization.$(NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: $(AUTHORINO_INSTANCE)-ca
  secretName: $(AUTHORINO_INSTANCE)-server-cert
