# This is the main Kustomization file to install Authorino.
# It includes the installation of the CRD and RBAC required to later deploy an Authorino instance.
# Warning! Modifications to this file or to its referenced parts may affect the bundle that is served by the Authorino Operator.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd
- rbac

namePrefix: authorino-
