name: End-to-end Tests

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Authorino Git ref to test
        required: false
      operatorVersion:
        description: Authorino Operator version. Changes to Authorino manifests (CRD, RBAC) in the tested branch will override the base manifests pulled from the Operator.
        required: true
        default: latest

jobs:
  e2e-tests:
    name: End-to-end Tests
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.gitRef || github.sha }}
      - name: Run make e2e
        env:
          OPERATOR_VERSION: ${{ github.event.inputs.operatorVersion }}
        run: |
          make e2e
